---
title: 1 Biases and Blunders
bibliography: ../references.bib
---

::: callout-note
This chapter starts by explaining the two systems that we have when we think: the quick one that can provide innacurate information, and the slower one that is much more accurate. Then, the chapter goes deeper into the 'Rules of Thumb' that we use when we use the quick system to make decisions and to judge, and that explains why it can be innacurate. Examples include the rule of representativeness, and giving meaning to randomness. (by Natsha)
:::

# Status quo bias, really for all?

::: author
By: Ariane
:::

::: highlight-quote
Free subscriptions seem like a bargain, even if the magazines rarely get read, so Sunstein happily made his choices. What he didn’t realize was that unless he took some action to cancel his subscription, he would continue to receive the magazines, paying for them at the normal rate. For about a decade, he has continued to subscribe to magazines that he hardly ever reads. (...) One of the causes of status quo bias is a lack of attention. Many people adopt what we will call the “yeah, whatever” heuristic.” (p.35)
:::

- This example happened in the context of the chapter Biases and blunders, when the status quo bias is demonstrated. According to Scribbr, “status quo bias refers to people’s preference for keeping things the way they currently are. Under status quo bias, people perceive change as a risk or a loss. Because of this, they try to maintain the current situation. This can impact the quality of their decisions.” (https://www.scribbr.com/research-bias/status-quo-bias/)
- The example of the subscription to a payable newspaper is not working in all situations because of the socioeconomic dimension of it. This reasoning works only for people who have a comfortable way of life, who can pay for a newspaper they even don’t read, who don’t take the time to check where money goes and so on. In all this part of the book, the author makes an abstraction of the socioeconomic constraints which modulate the status quo bias.
- Several studies observe the effect of the status quo bias on different cases. For instance, the Foundation for Studies and Research on International Development (FERDI, https://hdl.handle.net/10419/269762) highlights the influence of social capital on the status quo bias : the greater you have, the more you are in a situation where you can exchange information, learn and revise your practices in front of a status quo bias. Thus we are less likely to have status quo bias if we have an important social capital.
- Moreover, if we are aware of the status quo bias, we will think more about it for every situation and it gives less influence to the status quo bias on our decision.
- In conclusion, status quo bias matters, but we have to take into account that its influence depends on a lot of factors such as the socioeconomic conditions of the situation and the social capital of the individual.

# Accurate AIDS risk perceptions?

::: author
By: Taïna
:::

::: highlight-quote
“Gay men systematically underestimate the chance that they will contract AIDS, even though they know about AIDS risks in general” (p.XX)
:::

- only data are about : Health Optimism (α = 0.791) and Transmission Optimism (α = 0.795) 
- technical knowledge, experience, desire, and attitudes to risk may all affect how people respond and often in multiple, sometimes contradictory, directions.
- HIV optimism should be complemented by analysis of the complexities of individuals' assessments of both risk and pleasure in specific sexual contexts.
- \[**study of n=122 men**\] No effect on unrealistic optimism was found. It seems that the cognitive account provides a better explanation than does the motivational account of at least that form of UO measured in this study. Implications for AIDS education are discussed.
- Knowledge of HIV status among gay men and other men who have sex with men who are living with HIV was three times higher in countries with the least repressive lesbian, gay, bisexual and transgender people (LGBT) laws than in countries with the most repressive LGBT laws (8).
- Surveys in sub-Saharan Africa found that between 10% and 40% of gay men and other men who have sex with men delay or avoid health care due to fear of stigma --> gay men might not be “underestimating” the chance of getting aids, but fearing stigma. 
- stigma and discrimination create barriers across the HIV prevention, [testing and treatment cascades and reduce the impact of the AIDS response](https://www.unaids.org/en/resources/documents/2017/confronting-discrimination): "people living with HIV who perceive high levels of HIV-related stigma are 2.4 times more likely to delay enrolment in care until they are very ill (1). In eight countries with available data, more than a quarter of people living with HIV reported that they had avoided going to a local clinic in the previous 12 months because of their HIV status (Figure 1) (2). Such fears also discourage the uptake of prevention and testing services. For example, fear of the HIV-related stigma and discrimination that may result from an HIV-positive test result and having that result disclosed to others, either through self-disclosure or otherwise, has been identified as a disincentive to HIV testing in a range of settings (3, 4)." 

# Assigning meaning to randomness

::: author
By: Natsha
:::

::: highlight-quote
“Use of the representativeness heuristic can cause serious misperceptions of patterns in everyday life. When events are determined by chance, such as a sequence of coin tosses, people expect the resulting string of heads and tails to be representative of what they think of as random. \[...\] You might flip a coin three times, see it come up heads every time, and conclude that there is something funny about the coin. But the fact is that if you flip any coin a lot, it won’t be so unusual to see three heads in a row.”(p.27)
:::


The authors write that people tend to assign meaning to randomness even when there isn’t any. 

- Although the authors do not provide a source, their finding is correct. 
- The authors use the example of the coin tosses to illustrate how inaccurate the perception of randomness is. However, the example of the coin is not based on any study; the sources are not cited. 
- In their seminal work on heuristics and biases, Daniel Kahneman and Amos Tversky demonstrated how the representativeness heuristic can lead people to misjudge probabilities and see patterns even though they do not exist [@kahneman1972].
-   Tversky and Kahneman introduced the heuristics-and-biases (HB) research program with their research and were cited by 8841 papers on Google Scholar and were subject of meat-analyses such as “The heuristics-and-biases inventory: An open-source tool to explore individual differences in rationality” (Vincent Berthet, and Vincent de Gardelle, 2023).
-   More specifically, studies have been made on coin tosses and the perception of randomness. They have shown that people tend to erroneously rate sequences with less internal structure or order (such as HTTHT, with H being heads and T being tails) as more probable than sequences containing more structure or order (such as HHHHH) [@reimers2018].
