---
title: "9 Privatizing Social Security: Smorgasbord Style"
bibliography: ../references.bib
---

::: callout-note
This chapter examines Bush's proposal to partially privatize Social Security, similar to Sweden's system, where payroll taxes would go into individual savings accounts. Sweden's plan emphasized choice, offering many fund options and encouraging active selection. However, many chose poorly, resulting in higher fees and lower returns compared to the well-designed default fund. This highlights the need for better nudges in Social Security reform to guide better investment decisions. (by Marion S.)
:::

# Are women more organized?

::: author
By: Marion S. & Anaïs
:::

::: highlight-quote
(We have a theory about why women were more likely to make active choices: we think that women were less likely to lose the enrollment forms, and more likely to remember to mail them in. We admit to having no data to support this theory, and plead guilty to the possibility that we are being overly influenced—via the availability bias—by the fact that our significant others are considerably more organized than we are.)”(p.159)
:::

- In this excerpt, the author acknowledges that he's not relying on data, but on biases specific to his environment. We therefore sought to verify that women are indeed more involved in administrative tasks than me .
- According to a survey including 6875 tenure and tenure-track faculty at 140 US institutions, female academics reported to spend, on average, o.6 hours more per week than males on admin. Another survey covering 1378 faculty, women perform 12.4 admin activities per year, compared to men who just do 10.9. This shows that women may be more used to manage administrative work, to which we could associate active choices of the study. From this, we mightassume that—as the authors say–women are less likely to lose the enrolment forms, and more likely to remember to mail them in because they are more used to that kind of work (ex: administrative work) than men. 
- The research by Richard Hoggart, Olivier Schwartz, and Bernard Lahire underscores the pivotal role that women play in handling administrative and domestic tasks in traditional working-class families.
Hoggart's studies in Leeds, spanning the 1930s to 1950s, revealed that mothers were mainly responsible for managing interactions with institutions, often facing long waits and disrespect from staff.
Schwartz, examining large residential areas in the 1980s, found that mothers took a leading role in dealing with institutions. This was a key part of their maternal duties, encompassing both the "charge" and "government" of the family, where they held control over domestic matters.
In La raison des plus faibles (1993), Bernard Lahire highlighted the significant role women play in domestic record-keeping, including managing accounts, using calendars, creating to-do lists, and other forms of household organization. Mothers functioned as the family's memory, exhibiting a strong tendency towards planning and rational management of the home. 
More recent studies, such as that by Yasmin Siblot, confirm this and emphasize this phenomenon in lower-middle-class families. 
There's a paradox here: women haven't always taken care of administrative tasks. Less than a century ago, women couldn't even have a bank account.  It seems obvious that women are not naturally  predisposed to administrative tasks, but that culture has forced it upon them.

Finally, using their personal experience in this context as an argument is not without consequences: stereotypes are self-fulfilling, as numerous studies confirm for example, the study carried out by Steel & al in 20192 shows how intellectual performance can be affected by stereotypes. . By asserting this, the authors are not only influencing themselves not to change their personal situation, but they are also contributing to the transmission of this stereotype.

**References**

- Gal, D., & Rucker, D. D. (2018). The Loss of Loss Aversion: Will It Loom Larger Than Its Gain? Journal of Consumer Psychology, 28(3), 497–516. https://doi.org/10.1002/jcpy.1047
- Giraud, F. (2008, octobre 14). La prise en charge féminine des tâches administratives [Billet]. Socio-Voce. https://doi.org/10.58079/ug3q
- Siblot, Y. (2006). « Je suis la secrétaire de la famille ! » La prise en charge féminine des tâches administratives entre subordination et ressource. Genèses, 64(3), 46‑66. https://doi.org/10.3917/gen.064.0046
- Bonnet, C., Cambois, E., Cases, C., & Gaymu, J. (2011). La dépendance : Aujourd’hui l’affaire des femmes, demain davantage celle des hommes ? Population & Sociétés, 483(10), 1‑4. https://doi.org/10.3917/popsoc.483.0001
- Ernst, B. (1994). Lahire (Bernard). —La raison des plus faibles. Rapport au travail, écritures domestiques et lectures en milieux populaires. Revue française de pédagogie, 108(1), 148‑152.
- Steele, C. M., & Aronson, J. (1995). Stereotype threat and the intellectual test performance of African Americans. Journal of Personality and Social Psychology, 69(5), 797‑811. https://doi.org/10.1037/0022-3514.69.5.797
- https://physicsworld.com/a/female-academics-do-more-admin-than-their-male-colleagues/


