---
title: 13 Improving School Choices
bibliography: ../references.bib
---

::: callout-note
School choice has been a polarizing issue in American politics. The idea is that the competition improves education quality and combined with vouchers for impoverished people gives everyone a fair chance. There are those who accepts this idea and those should criticise it. School choice could be enhanced by helping parents and children making better choices , this is where nudges come at play. San Marcos initiative is told to nudge students towards applying to college. (by Sofia)
:::

# Why didn't the educational program NCLB work ?

::: author
By: Sarah G. & Charlotte
:::

::: highlight-quote
"By June 2003 twelve of Worcester’s fifty public schools had
been labeled “in need of improvement” for two consecutive years, and five
for three consecutive years. That summer, forty-seven hundred students,
almost one-fifth the district’s student population, were eligible to transfer,
and eighteen hundred students had the right to collect federal money for
supplemental education services. But six months later, only one student
had switched schools, and only two had taken advantage of supplemental
services! Worcester officials themselves were primarily responsible."
:::

The author’s argument is mostly based on an article by William G. Howell (Sydney Stein Professor in American Politics in the Harris School and co-director of the Program on Political Institutions) published in Education Next (journal that provides news and research to bring evidence to bear on current education policy).
In his book, the author then argues that the education program NCLB didn’t work and that this was the fault of the officials themselves. We hence want to fact-check his argument.

Indeed, by relying on many sources, we found that the program didn’t work:
“The impact of NCLB was supposed to be felt most strongly in urban centers with large minority and disadvantaged populations-places just like Worcester. Instead, during its first two years, NCLB appeared to have little impact at all ». In addition, we found that officials indeed discouraged families to transfer their child to better performing schools: “Ultimately, districts are responsible for informing parents of their rights and opportunities under NCLB. But given the challenges that Worcester faces, along with the incentives to safeguard public finances, it should come as no surprise that administrators subtly, and not so subtly, discouraged families from transferring their children out of underperforming schools.” More precisely, the district notified families through a letter at underperforming schools of their rights under NCLB. In their letter, officials noted that because of space limitations, they may not be able to transfer every child in a family to the same school. Also, they affirmed that families with children at underperforming schools who switch schools would forfeit their rights to supplemental services. Also they cited improvements of Worcester public schools. All these affirmations discouraged families to transfer their children to new school. 

Références :

- https://www.educationnext.org/one-child-at-a-time/
- FOUCAULT Marc, « « No child left behind » : entre espoir et déception », Administration & Éducation, 2017/3 (N° 155), p. 29-33. DOI : 10.3917/admed.155.0029. URL : https://www.cairn.info/revue-administration-et-education-2017-3-page-29.html 

# Analyzing the San Marcos High School Initiative

::: author
By: Micaela & Sofia
:::

::: highlight-quote
“The nudge was this: in order to graduate from San Marcos High, a student would have to complete an application to nearby Austin Community College. 
In San Marcos, schools run on a tight budget, and two-thirds of high schoolers never experience higher education. The superintendent had no outside funding to implement the idea, so she asked her teachers and the community college for help…
In the end, the nudge produced big results. From 2004 to 2005 the percentage of San Marcos High students who went to Texas colleges rose 11 percentage points, to 45 percent. (p.206)”
:::

What do we want to fact-check: 

We want to find official data, plus, one can ask oneself how mindful is the choice of increased enrollment as a proxy for assessing nudge efficiency. Enrolling in a university doesn't mean finishing it, thus, some additional data, such as the percentage of students that didn’t drop out the first year, would be helpful to better assess the situation. 

Fact-check: 

1. Having checked all references and bibliography provided by the author, as well as having searched this information on web (Google), Google scholar and a couple other search engines, we didn’t find any study on San Marcos high schools for the specified time period. 

2. Thus, we concluded that the data might be directly taken from official Texas Education websites. San Marcos is situated in Texas in Hays county, there were several schools there in the studied period (2003-2005) : San Marcos High School ( school number 105902001) and Pride High School (school number 105902002, closed in 2010). According to report on the Texas Higher Education Data website, in 2003-2004 there were 306 highschool graduate students in San Marcos High School, from whom only 47 were enrolled in Texas colleges and 86 were enrolled in Texas universities;  in Pride High School there were 89 high school graduates, from whom 6 were enrolled in a Texas College (Austin Community College). Thus, in 2004, around 13,4 % of high school graduates were enrolled in Texas colleges and 35,2 % of high school graduates were enrolled either in a college or a university in Texas. 
In 2004-2005 in San Marcos high school there were 316 high school graduates, from whom 47 were enrolled in Texas colleges and 80 were enrolled in Texas universities; in Pride High School there were 84 students and only 7 were enrolled in Texas Colleges (Austin Community College). 13,5 % of students were enrolled in Texas colleges and 33,5 % of students were enrolled either in a Texas College or University. So, we observe no significant increase in percentage of students enrolled in College (0,01), and we observe a decrease in the proportion of students enrolled in Texas universities and colleges. In the citation “colleges” presumably include both colleges and universities, otherwise percentages are too far from the described 45 %. As it can be seen in these two documents there are also other institutions mentioned (other pub/ind 4-yr or 2-yr institutions), if we include them into calculations, we observe that 41,5 % of students were enrolled in some institution in 2005 which is closer to the mentioned 45 in the cited paragraph. Nevertheless, according to citation, we should observe (45-11)=34% enrollment in 2004. If we include other pub/ind 4-yr or 2-yr institutions, we receive 44,6% enrolment in 2004. So, there percentage of students enrolled in some higher education institutions decreased, rather than increased.

**Note**: 
We took a glance at the 2002-2003 report where there were 33,5 % of students enrolled in Texas colleges and universities (there is no division of school, they are united under the name of the district). Therefore, there was a positive change but between fall 2003 and 2004, not between fall 2004 and fall 2005. The data in fall 2004 and 2003 corresponds to the citation. 

If our calculations are correct, this means that: 

- Either the authors didn’t use the data we use, which is the official data of the Texas Higher Education data websites
- Either the data has been changed 
- Either in 2005 the percentage, including other pub/ind 4-yr or 2-yr institutions was used (41,5 %), while in 2004 other pub/ind 4-yr or 2-yr institutions weren’t  included (33,5%), which could create a gap described in the citation (still not 11 %)

Here we provided possible criticism of the described nudge:

- The citation makes it seem like the increase in college enrollment was solely due to the nudges. However, other factors could have played a role, such as broader educational initiatives, economic changes, or community support, which aren't mentioned.
- The program worked well at San Marcos High, but it might not be as effective in other schools with different demographics or fewer resources. Every school has unique challenges, so what works in one place might not work in another.
- The citation says the superintendent had no outside funding and had to rely on existing resources. This could put a strain on those resources, making the program hard to sustain. Schools without community support might find it even harder to implement similar programs without extra funding.

**References**

- Texas Higher Education Coordinating Board and Texas Education Agency,（2008),  “Texas High School Graduates From FY 2005 Enrolled in Texas Public or Independent Higher Education Fall 2005” 
https://apps.highered.texas.gov/DocID/pdf%5C1161.pdf 

- Texas Higher Education Coordinating Board and Texas Education Agency,（2008),  “Texas High School Graduates From FY 2004 Enrolled in Texas Public or Independent Higher Education Fall 2004”
https://apps.highered.texas.gov/DocID/pdf%5C0963.pdf

- THED: High School Graduates Enrolled in Higher Education. (n.d.). Retrieved June 14, 2024, from http://www.txhighereddata.org/index.cfm?objectid=77D62E90-D970-11E8-BB650050560100A9

# Voucher and charter school programs

::: author
By: Anouk
:::

::: highlight-quote
“Carolyn Hoxby, a leading economist who has analyzed both voucher and charter school programs, finds that when facing competition, public schools produce higher student achievement per dollar spent. Test-score improvements can range from 1 to 7 percent a year depending on the school and student—and improvement is usually greatest among younger students, low-income students, and minority-group members.” (p.100)
:::

**Context**: 
In the chapter the authors discuss how to help parents choose schools for their  children. 
School choice has mostly been an option only for rich people: children are usually assigned to the public school nearest their home. If the parents can afford it, they can avoid this assignment by sending their children to (expensive) private schools. In the 1950's, [based on ideas of the economist Milton Friedman](https://en.wikipedia.org/wiki/School_choice ), school choice should be made broadly available to everyone - and not only the rich. In the US, some states use or have at least at some point experimented with so-called "school vouchers". There are also other school choice options allowing students to attend public school, such as charter schools, magnet schools, homeschooling, etc… Essentially, the state guarantees to pay tuition fees for students at a school of the parents' choice, no matter if they choose public or private, religious or non-religious school options. Just after this quote, the authors try to make programs helping parents to make better choices, after being given this opportunity.

**Argument**: 
The chapter is mostly on how to help parents make better choices. The authors take for granted that school choice is obviously a good thing: they self-identify as "libertarians", who "are strongly inclined to support the concept of school choice” (p.100). Their argument in favor of school choice is that if parents can pick the school for their children, that will spur competition among schools. Competition will motivate schools to be better (because they have to outperform each other), ultimately resulting in better education for everyone. And if schools compete, those who are the least advantaged have the most to gain. 

**Fact-check**: In the present quote, they present evidence in favor of the benefits of school choice. [The study by Hoxby (2001)](https://www.csus.edu/indiv/h/howellj/econ145_f2009/handouts/bettinger_eer.pdf) is, it seems, part of testing a privatization project in Michigan in the 1990s. A bunch of charter schools opened in Michigan, thereby increasing competition. As a consequence, economists did indeed observe better performance of children in public schools. But was it because competition made the schools better? Probably not. Instead, the composition of classes in public schools changed. Charter schools tended to take the lowest performing kids from public schools, in fact they found “that test scores of charter school students do not improve, and may actually decline, relative to those of public school students”. Unsurprisingly, the test scores at the public schools went up - their most struggling students were at other schools no. By contrast, performance at charter schools tended to drop, despite the increased competition, so the results suggest “that charter schools have had no significant effect on test scores in neighboring public schools”. 

Moreover, concerning voucher programs, [a report by the Economic Policy Institute](https://files.eric.ed.gov/fulltext/ED579337.pdf ) analyzes studies in several U.S. cities, the states of Florida, Indiana, Louisiana, and in Chile and India, finding “limited improvements at best in student achievement and school district performance from even large-scale programs. In the few cases in which test scores increased, other factors, namely increased public accountability, not private school competition, seem to be more likely drivers.” Supporting and strengthening neighborhood public schools with a menu of proven policies would be better for accomplishing these achievements. 

We also have to take into account that actual performance of school choice programs - such as voucher or charter schools programs - is assessed only by students' academic results. Maybe other ways of measuring have to be considered to avoid some spurious correlations, in studies, between programs and the U.S. achievements. 
